<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/01 20:30:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bdsea',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
