<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/10 21:04:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=bdsea',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
