<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/07/10 21:46:52
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'indexlogin' => 
  array (
    'is_secure' => false,
  ),
);
