<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ACCION', 'doctrine');

/**
 * BaseACCION
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idaccion
 * @property string $codaccion
 * @property string $nombreaccion
 * @property string $urlaccion
 * @property integer $idmodulo
 * @property MODULO $MODULO
 * @property Doctrine_Collection $ACCIONXPERFIL
 * 
 * @method integer             getIdaccion()      Returns the current record's "idaccion" value
 * @method string              getCodaccion()     Returns the current record's "codaccion" value
 * @method string              getNombreaccion()  Returns the current record's "nombreaccion" value
 * @method string              getUrlaccion()     Returns the current record's "urlaccion" value
 * @method integer             getIdmodulo()      Returns the current record's "idmodulo" value
 * @method MODULO              getMODULO()        Returns the current record's "MODULO" value
 * @method Doctrine_Collection getACCIONXPERFIL() Returns the current record's "ACCIONXPERFIL" collection
 * @method ACCION              setIdaccion()      Sets the current record's "idaccion" value
 * @method ACCION              setCodaccion()     Sets the current record's "codaccion" value
 * @method ACCION              setNombreaccion()  Sets the current record's "nombreaccion" value
 * @method ACCION              setUrlaccion()     Sets the current record's "urlaccion" value
 * @method ACCION              setIdmodulo()      Sets the current record's "idmodulo" value
 * @method ACCION              setMODULO()        Sets the current record's "MODULO" value
 * @method ACCION              setACCIONXPERFIL() Sets the current record's "ACCIONXPERFIL" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseACCION extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ACCION');
        $this->hasColumn('idaccion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('codaccion', 'string', 5, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             ));
        $this->hasColumn('nombreaccion', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('urlaccion', 'string', 300, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 300,
             ));
        $this->hasColumn('idmodulo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MODULO', array(
             'local' => 'idmodulo',
             'foreign' => 'idmodulo'));

        $this->hasMany('ACCIONXPERFIL', array(
             'local' => 'idaccion',
             'foreign' => 'idaccion'));
    }
}