<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MUNICIPIO', 'doctrine');

/**
 * BaseMUNICIPIO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idmunicipio
 * @property string $nombremunicipio
 * @property Doctrine_Collection $ACADEMICO
 * @property Doctrine_Collection $DIRECCION
 * 
 * @method integer             getIdmunicipio()     Returns the current record's "idmunicipio" value
 * @method string              getNombremunicipio() Returns the current record's "nombremunicipio" value
 * @method Doctrine_Collection getACADEMICO()       Returns the current record's "ACADEMICO" collection
 * @method Doctrine_Collection getDIRECCION()       Returns the current record's "DIRECCION" collection
 * @method MUNICIPIO           setIdmunicipio()     Sets the current record's "idmunicipio" value
 * @method MUNICIPIO           setNombremunicipio() Sets the current record's "nombremunicipio" value
 * @method MUNICIPIO           setACADEMICO()       Sets the current record's "ACADEMICO" collection
 * @method MUNICIPIO           setDIRECCION()       Sets the current record's "DIRECCION" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMUNICIPIO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('MUNICIPIO');
        $this->hasColumn('idmunicipio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombremunicipio', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ACADEMICO', array(
             'local' => 'idmunicipio',
             'foreign' => 'idmunicipionac'));

        $this->hasMany('DIRECCION', array(
             'local' => 'idmunicipio',
             'foreign' => 'idmunicipiodir'));
    }
}