<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TIPO_SANGRE', 'doctrine');

/**
 * BaseTIPO_SANGRE
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtiposangre
 * @property string $nombretiposangre
 * @property Doctrine_Collection $ACADEMICO
 * 
 * @method integer             getIdtiposangre()     Returns the current record's "idtiposangre" value
 * @method string              getNombretiposangre() Returns the current record's "nombretiposangre" value
 * @method Doctrine_Collection getACADEMICO()        Returns the current record's "ACADEMICO" collection
 * @method TIPO_SANGRE         setIdtiposangre()     Sets the current record's "idtiposangre" value
 * @method TIPO_SANGRE         setNombretiposangre() Sets the current record's "nombretiposangre" value
 * @method TIPO_SANGRE         setACADEMICO()        Sets the current record's "ACADEMICO" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTIPO_SANGRE extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TIPO_SANGRE');
        $this->hasColumn('idtiposangre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombretiposangre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ACADEMICO', array(
             'local' => 'idtiposangre',
             'foreign' => 'idtiposangre'));
    }
}