<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TIEMPO_CONTRATACION', 'doctrine');

/**
 * BaseTIEMPO_CONTRATACION
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtiempocontratacion
 * @property string $nombretiempocontratacion
 * @property Doctrine_Collection $HISTORIAL_CARGO
 * 
 * @method integer             getIdtiempocontratacion()     Returns the current record's "idtiempocontratacion" value
 * @method string              getNombretiempocontratacion() Returns the current record's "nombretiempocontratacion" value
 * @method Doctrine_Collection getHISTORIALCARGO()           Returns the current record's "HISTORIAL_CARGO" collection
 * @method TIEMPO_CONTRATACION setIdtiempocontratacion()     Sets the current record's "idtiempocontratacion" value
 * @method TIEMPO_CONTRATACION setNombretiempocontratacion() Sets the current record's "nombretiempocontratacion" value
 * @method TIEMPO_CONTRATACION setHISTORIALCARGO()           Sets the current record's "HISTORIAL_CARGO" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTIEMPO_CONTRATACION extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TIEMPO_CONTRATACION');
        $this->hasColumn('idtiempocontratacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombretiempocontratacion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('HISTORIAL_CARGO', array(
             'local' => 'idtiempocontratacion',
             'foreign' => 'idtiempocontratacion'));
    }
}