<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('IDIOMA', 'doctrine');

/**
 * BaseIDIOMA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ididioma
 * @property string $codisoidioma
 * @property string $nombreisoidioma
 * @property Doctrine_Collection $ACADEMICOXIDIOMA
 * 
 * @method integer             getIdidioma()         Returns the current record's "ididioma" value
 * @method string              getCodisoidioma()     Returns the current record's "codisoidioma" value
 * @method string              getNombreisoidioma()  Returns the current record's "nombreisoidioma" value
 * @method Doctrine_Collection getACADEMICOXIDIOMA() Returns the current record's "ACADEMICOXIDIOMA" collection
 * @method IDIOMA              setIdidioma()         Sets the current record's "ididioma" value
 * @method IDIOMA              setCodisoidioma()     Sets the current record's "codisoidioma" value
 * @method IDIOMA              setNombreisoidioma()  Sets the current record's "nombreisoidioma" value
 * @method IDIOMA              setACADEMICOXIDIOMA() Sets the current record's "ACADEMICOXIDIOMA" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIDIOMA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('IDIOMA');
        $this->hasColumn('ididioma', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('codisoidioma', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('nombreisoidioma', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ACADEMICOXIDIOMA', array(
             'local' => 'ididioma',
             'foreign' => 'ididioma'));
    }
}