<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CARGOXUNIDAD_ORG', 'doctrine');

/**
 * BaseCARGOXUNIDAD_ORG
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcargoxunidadorg
 * @property integer $idcargo
 * @property integer $idunidadorganizativa
 * @property UNIDAD_ORGANIZATIVA $UNIDAD_ORGANIZATIVA
 * @property CARGO $CARGO
 * @property Doctrine_Collection $HISTORIAL_CARGO
 * 
 * @method integer             getIdcargoxunidadorg()    Returns the current record's "idcargoxunidadorg" value
 * @method integer             getIdcargo()              Returns the current record's "idcargo" value
 * @method integer             getIdunidadorganizativa() Returns the current record's "idunidadorganizativa" value
 * @method UNIDAD_ORGANIZATIVA getUNIDADORGANIZATIVA()   Returns the current record's "UNIDAD_ORGANIZATIVA" value
 * @method CARGO               getCARGO()                Returns the current record's "CARGO" value
 * @method Doctrine_Collection getHISTORIALCARGO()       Returns the current record's "HISTORIAL_CARGO" collection
 * @method CARGOXUNIDAD_ORG    setIdcargoxunidadorg()    Sets the current record's "idcargoxunidadorg" value
 * @method CARGOXUNIDAD_ORG    setIdcargo()              Sets the current record's "idcargo" value
 * @method CARGOXUNIDAD_ORG    setIdunidadorganizativa() Sets the current record's "idunidadorganizativa" value
 * @method CARGOXUNIDAD_ORG    setUNIDADORGANIZATIVA()   Sets the current record's "UNIDAD_ORGANIZATIVA" value
 * @method CARGOXUNIDAD_ORG    setCARGO()                Sets the current record's "CARGO" value
 * @method CARGOXUNIDAD_ORG    setHISTORIALCARGO()       Sets the current record's "HISTORIAL_CARGO" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCARGOXUNIDAD_ORG extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CARGOXUNIDAD_ORG');
        $this->hasColumn('idcargoxunidadorg', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idcargo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idunidadorganizativa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UNIDAD_ORGANIZATIVA', array(
             'local' => 'idunidadorganizativa',
             'foreign' => 'idunidadorganizativa'));

        $this->hasOne('CARGO', array(
             'local' => 'idcargo',
             'foreign' => 'idcargo'));

        $this->hasMany('HISTORIAL_CARGO', array(
             'local' => 'idcargoxunidadorg',
             'foreign' => 'idcargoxunidadorg'));
    }
}