<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CATEGORIA_UMA', 'doctrine');

/**
 * BaseCATEGORIA_UMA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idcategoriauma
 * @property integer $numnivelcategoriauma
 * @property string $nombrecategoriauma
 * @property string $descripcioncategoriauma
 * @property integer $idcategoriaumasup
 * @property Doctrine_Collection $CATEGORIA_UMA
 * @property Doctrine_Collection $ACTIVIDAD_UMA
 * 
 * @method integer             getIdcategoriauma()          Returns the current record's "idcategoriauma" value
 * @method integer             getNumnivelcategoriauma()    Returns the current record's "numnivelcategoriauma" value
 * @method string              getNombrecategoriauma()      Returns the current record's "nombrecategoriauma" value
 * @method string              getDescripcioncategoriauma() Returns the current record's "descripcioncategoriauma" value
 * @method integer             getIdcategoriaumasup()       Returns the current record's "idcategoriaumasup" value
 * @method Doctrine_Collection getCATEGORIAUMA()            Returns the current record's "CATEGORIA_UMA" collection
 * @method Doctrine_Collection getACTIVIDADUMA()            Returns the current record's "ACTIVIDAD_UMA" collection
 * @method CATEGORIA_UMA       setIdcategoriauma()          Sets the current record's "idcategoriauma" value
 * @method CATEGORIA_UMA       setNumnivelcategoriauma()    Sets the current record's "numnivelcategoriauma" value
 * @method CATEGORIA_UMA       setNombrecategoriauma()      Sets the current record's "nombrecategoriauma" value
 * @method CATEGORIA_UMA       setDescripcioncategoriauma() Sets the current record's "descripcioncategoriauma" value
 * @method CATEGORIA_UMA       setIdcategoriaumasup()       Sets the current record's "idcategoriaumasup" value
 * @method CATEGORIA_UMA       setCATEGORIAUMA()            Sets the current record's "CATEGORIA_UMA" collection
 * @method CATEGORIA_UMA       setACTIVIDADUMA()            Sets the current record's "ACTIVIDAD_UMA" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCATEGORIA_UMA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CATEGORIA_UMA');
        $this->hasColumn('idcategoriauma', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('numnivelcategoriauma', 'integer', 2, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('nombrecategoriauma', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('descripcioncategoriauma', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('idcategoriaumasup', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CATEGORIA_UMA', array(
             'local' => 'idcategoriauma',
             'foreign' => 'idcategoriaumasup'));

        $this->hasMany('ACTIVIDAD_UMA', array(
             'local' => 'idcategoriauma',
             'foreign' => 'idcategoriauma'));
    }
}