<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ESTADO_CIVIL', 'doctrine');

/**
 * BaseESTADO_CIVIL
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idestadocivil
 * @property string $nombreestadocivil
 * @property Doctrine_Collection $ACADEMICO
 * 
 * @method integer             getIdestadocivil()     Returns the current record's "idestadocivil" value
 * @method string              getNombreestadocivil() Returns the current record's "nombreestadocivil" value
 * @method Doctrine_Collection getACADEMICO()         Returns the current record's "ACADEMICO" collection
 * @method ESTADO_CIVIL        setIdestadocivil()     Sets the current record's "idestadocivil" value
 * @method ESTADO_CIVIL        setNombreestadocivil() Sets the current record's "nombreestadocivil" value
 * @method ESTADO_CIVIL        setACADEMICO()         Sets the current record's "ACADEMICO" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseESTADO_CIVIL extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ESTADO_CIVIL');
        $this->hasColumn('idestadocivil', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombreestadocivil', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ACADEMICO', array(
             'local' => 'idestadocivil',
             'foreign' => 'idestadocivil'));
    }
}