<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TIPO_CONTRATACION_EX', 'doctrine');

/**
 * BaseTIPO_CONTRATACION_EX
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipocontratacionex
 * @property string $nombretipocontratacionex
 * @property Doctrine_Collection $HISTORIAL_CARGO
 * 
 * @method integer              getIdtipocontratacionex()     Returns the current record's "idtipocontratacionex" value
 * @method string               getNombretipocontratacionex() Returns the current record's "nombretipocontratacionex" value
 * @method Doctrine_Collection  getHISTORIALCARGO()           Returns the current record's "HISTORIAL_CARGO" collection
 * @method TIPO_CONTRATACION_EX setIdtipocontratacionex()     Sets the current record's "idtipocontratacionex" value
 * @method TIPO_CONTRATACION_EX setNombretipocontratacionex() Sets the current record's "nombretipocontratacionex" value
 * @method TIPO_CONTRATACION_EX setHISTORIALCARGO()           Sets the current record's "HISTORIAL_CARGO" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTIPO_CONTRATACION_EX extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TIPO_CONTRATACION_EX');
        $this->hasColumn('idtipocontratacionex', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombretipocontratacionex', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('HISTORIAL_CARGO', array(
             'local' => 'idtipocontratacionex',
             'foreign' => 'idtipocontratacionex'));
    }
}