<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ACADEMICO', 'doctrine');

/**
 * BaseACADEMICO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idacademico
 * @property string $codigoacademico
 * @property string $primernombreacad
 * @property string $segundonombreacad
 * @property string $primerapellidoacad
 * @property string $segundoapellidoacad
 * @property string $apellidocasadaacad
 * @property integer $sexoacad
 * @property date $fechanacimientoacad
 * @property integer $esnacional
 * @property integer $esescalafonado
 * @property integer $espensionado
 * @property integer $esjubilado
 * @property integer $usalentes
 * @property integer $poseetransporte
 * @property integer $idpaisnac
 * @property integer $idestadonac
 * @property integer $idciudadnac
 * @property integer $idpaisciudadania
 * @property integer $idtiposangre
 * @property integer $idnivelestudio
 * @property integer $idestadocivil
 * @property integer $idusuario
 * @property USUARIO $USUARIO
 * @property CIUDAD $CIUDAD
 * @property CIUDAD $CIUDAD_3
 * @property CIUDAD $CIUDAD_4
 * @property ESTADO_CIVIL $ESTADO_CIVIL
 * @property NIVEL_ESTUDIO $NIVEL_ESTUDIO
 * @property PAIS $PAIS
 * @property TIPO_SANGRE $TIPO_SANGRE
 * @property Doctrine_Collection $ACADEMICOXIDIOMA
 * @property Doctrine_Collection $ACADEMICOXMATERIA
 * @property Doctrine_Collection $ACTIVIDAD
 * @property Doctrine_Collection $CONTACTO_EMER
 * @property Doctrine_Collection $DIRECCION
 * @property Doctrine_Collection $DOC_IDENTIFICACION
 * @property Doctrine_Collection $HISTORIAL_CARGO
 * @property Doctrine_Collection $HISTORIAL_GRADO_ACAD
 * @property Doctrine_Collection $TEL_ACADEMICO
 * 
 * @method integer             getIdacademico()          Returns the current record's "idacademico" value
 * @method string              getCodigoacademico()      Returns the current record's "codigoacademico" value
 * @method string              getPrimernombreacad()     Returns the current record's "primernombreacad" value
 * @method string              getSegundonombreacad()    Returns the current record's "segundonombreacad" value
 * @method string              getPrimerapellidoacad()   Returns the current record's "primerapellidoacad" value
 * @method string              getSegundoapellidoacad()  Returns the current record's "segundoapellidoacad" value
 * @method string              getApellidocasadaacad()   Returns the current record's "apellidocasadaacad" value
 * @method integer             getSexoacad()             Returns the current record's "sexoacad" value
 * @method date                getFechanacimientoacad()  Returns the current record's "fechanacimientoacad" value
 * @method integer             getEsnacional()           Returns the current record's "esnacional" value
 * @method integer             getEsescalafonado()       Returns the current record's "esescalafonado" value
 * @method integer             getEspensionado()         Returns the current record's "espensionado" value
 * @method integer             getEsjubilado()           Returns the current record's "esjubilado" value
 * @method integer             getUsalentes()            Returns the current record's "usalentes" value
 * @method integer             getPoseetransporte()      Returns the current record's "poseetransporte" value
 * @method integer             getIdpaisnac()            Returns the current record's "idpaisnac" value
 * @method integer             getIdestadonac()          Returns the current record's "idestadonac" value
 * @method integer             getIdciudadnac()          Returns the current record's "idciudadnac" value
 * @method integer             getIdpaisciudadania()     Returns the current record's "idpaisciudadania" value
 * @method integer             getIdtiposangre()         Returns the current record's "idtiposangre" value
 * @method integer             getIdnivelestudio()       Returns the current record's "idnivelestudio" value
 * @method integer             getIdestadocivil()        Returns the current record's "idestadocivil" value
 * @method integer             getIdusuario()            Returns the current record's "idusuario" value
 * @method USUARIO             getUSUARIO()              Returns the current record's "USUARIO" value
 * @method CIUDAD              getCIUDAD()               Returns the current record's "CIUDAD" value
 * @method CIUDAD              getCIUDAD3()              Returns the current record's "CIUDAD_3" value
 * @method CIUDAD              getCIUDAD4()              Returns the current record's "CIUDAD_4" value
 * @method ESTADO_CIVIL        getESTADOCIVIL()          Returns the current record's "ESTADO_CIVIL" value
 * @method NIVEL_ESTUDIO       getNIVELESTUDIO()         Returns the current record's "NIVEL_ESTUDIO" value
 * @method PAIS                getPAIS()                 Returns the current record's "PAIS" value
 * @method TIPO_SANGRE         getTIPOSANGRE()           Returns the current record's "TIPO_SANGRE" value
 * @method Doctrine_Collection getACADEMICOXIDIOMA()     Returns the current record's "ACADEMICOXIDIOMA" collection
 * @method Doctrine_Collection getACADEMICOXMATERIA()    Returns the current record's "ACADEMICOXMATERIA" collection
 * @method Doctrine_Collection getACTIVIDAD()            Returns the current record's "ACTIVIDAD" collection
 * @method Doctrine_Collection getCONTACTOEMER()         Returns the current record's "CONTACTO_EMER" collection
 * @method Doctrine_Collection getDIRECCION()            Returns the current record's "DIRECCION" collection
 * @method Doctrine_Collection getDOCIDENTIFICACION()    Returns the current record's "DOC_IDENTIFICACION" collection
 * @method Doctrine_Collection getHISTORIALCARGO()       Returns the current record's "HISTORIAL_CARGO" collection
 * @method Doctrine_Collection getHISTORIALGRADOACAD()   Returns the current record's "HISTORIAL_GRADO_ACAD" collection
 * @method Doctrine_Collection getTELACADEMICO()         Returns the current record's "TEL_ACADEMICO" collection
 * @method ACADEMICO           setIdacademico()          Sets the current record's "idacademico" value
 * @method ACADEMICO           setCodigoacademico()      Sets the current record's "codigoacademico" value
 * @method ACADEMICO           setPrimernombreacad()     Sets the current record's "primernombreacad" value
 * @method ACADEMICO           setSegundonombreacad()    Sets the current record's "segundonombreacad" value
 * @method ACADEMICO           setPrimerapellidoacad()   Sets the current record's "primerapellidoacad" value
 * @method ACADEMICO           setSegundoapellidoacad()  Sets the current record's "segundoapellidoacad" value
 * @method ACADEMICO           setApellidocasadaacad()   Sets the current record's "apellidocasadaacad" value
 * @method ACADEMICO           setSexoacad()             Sets the current record's "sexoacad" value
 * @method ACADEMICO           setFechanacimientoacad()  Sets the current record's "fechanacimientoacad" value
 * @method ACADEMICO           setEsnacional()           Sets the current record's "esnacional" value
 * @method ACADEMICO           setEsescalafonado()       Sets the current record's "esescalafonado" value
 * @method ACADEMICO           setEspensionado()         Sets the current record's "espensionado" value
 * @method ACADEMICO           setEsjubilado()           Sets the current record's "esjubilado" value
 * @method ACADEMICO           setUsalentes()            Sets the current record's "usalentes" value
 * @method ACADEMICO           setPoseetransporte()      Sets the current record's "poseetransporte" value
 * @method ACADEMICO           setIdpaisnac()            Sets the current record's "idpaisnac" value
 * @method ACADEMICO           setIdestadonac()          Sets the current record's "idestadonac" value
 * @method ACADEMICO           setIdciudadnac()          Sets the current record's "idciudadnac" value
 * @method ACADEMICO           setIdpaisciudadania()     Sets the current record's "idpaisciudadania" value
 * @method ACADEMICO           setIdtiposangre()         Sets the current record's "idtiposangre" value
 * @method ACADEMICO           setIdnivelestudio()       Sets the current record's "idnivelestudio" value
 * @method ACADEMICO           setIdestadocivil()        Sets the current record's "idestadocivil" value
 * @method ACADEMICO           setIdusuario()            Sets the current record's "idusuario" value
 * @method ACADEMICO           setUSUARIO()              Sets the current record's "USUARIO" value
 * @method ACADEMICO           setCIUDAD()               Sets the current record's "CIUDAD" value
 * @method ACADEMICO           setCIUDAD3()              Sets the current record's "CIUDAD_3" value
 * @method ACADEMICO           setCIUDAD4()              Sets the current record's "CIUDAD_4" value
 * @method ACADEMICO           setESTADOCIVIL()          Sets the current record's "ESTADO_CIVIL" value
 * @method ACADEMICO           setNIVELESTUDIO()         Sets the current record's "NIVEL_ESTUDIO" value
 * @method ACADEMICO           setPAIS()                 Sets the current record's "PAIS" value
 * @method ACADEMICO           setTIPOSANGRE()           Sets the current record's "TIPO_SANGRE" value
 * @method ACADEMICO           setACADEMICOXIDIOMA()     Sets the current record's "ACADEMICOXIDIOMA" collection
 * @method ACADEMICO           setACADEMICOXMATERIA()    Sets the current record's "ACADEMICOXMATERIA" collection
 * @method ACADEMICO           setACTIVIDAD()            Sets the current record's "ACTIVIDAD" collection
 * @method ACADEMICO           setCONTACTOEMER()         Sets the current record's "CONTACTO_EMER" collection
 * @method ACADEMICO           setDIRECCION()            Sets the current record's "DIRECCION" collection
 * @method ACADEMICO           setDOCIDENTIFICACION()    Sets the current record's "DOC_IDENTIFICACION" collection
 * @method ACADEMICO           setHISTORIALCARGO()       Sets the current record's "HISTORIAL_CARGO" collection
 * @method ACADEMICO           setHISTORIALGRADOACAD()   Sets the current record's "HISTORIAL_GRADO_ACAD" collection
 * @method ACADEMICO           setTELACADEMICO()         Sets the current record's "TEL_ACADEMICO" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseACADEMICO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ACADEMICO');
        $this->hasColumn('idacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigoacademico', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('primernombreacad', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('segundonombreacad', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('primerapellidoacad', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('segundoapellidoacad', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('apellidocasadaacad', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('sexoacad', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('fechanacimientoacad', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('esnacional', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('esescalafonado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('espensionado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('esjubilado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('usalentes', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('poseetransporte', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('idpaisnac', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idestadonac', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idciudadnac', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idpaisciudadania', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idtiposangre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idnivelestudio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idestadocivil', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idusuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('USUARIO', array(
             'local' => 'idusuario',
             'foreign' => 'idusuario'));

        $this->hasOne('CIUDAD', array(
             'local' => 'idciudadnac',
             'foreign' => 'idciudad'));

        $this->hasOne('CIUDAD as CIUDAD_3', array(
             'local' => 'idestadonac',
             'foreign' => 'idestado'));

        $this->hasOne('CIUDAD as CIUDAD_4', array(
             'local' => 'idpaisnac',
             'foreign' => 'idpais'));

        $this->hasOne('ESTADO_CIVIL', array(
             'local' => 'idestadocivil',
             'foreign' => 'idestadocivil'));

        $this->hasOne('NIVEL_ESTUDIO', array(
             'local' => 'idnivelestudio',
             'foreign' => 'idnivelestudio'));

        $this->hasOne('PAIS', array(
             'local' => 'idpaisciudadania',
             'foreign' => 'idpais'));

        $this->hasOne('TIPO_SANGRE', array(
             'local' => 'idtiposangre',
             'foreign' => 'idtiposangre'));

        $this->hasMany('ACADEMICOXIDIOMA', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasMany('ACADEMICOXMATERIA', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasMany('ACTIVIDAD', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasMany('CONTACTO_EMER', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasMany('DIRECCION', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasMany('DOC_IDENTIFICACION', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasMany('HISTORIAL_CARGO', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasMany('HISTORIAL_GRADO_ACAD', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasMany('TEL_ACADEMICO', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));
    }
}