<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ACTIVIDAD', 'doctrine');

/**
 * BaseACTIVIDAD
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idacademico
 * @property integer $idactividad
 * @property string $nombreactividad
 * @property string $descripcionactividad
 * @property string $observacionactividad
 * @property integer $idtipoactividad
 * @property integer $idestadoactividad
 * @property ESTADO_ACTIVIDAD $ESTADO_ACTIVIDAD
 * @property ACADEMICO $ACADEMICO
 * @property TIPO_ACTIVIDAD $TIPO_ACTIVIDAD
 * @property Doctrine_Collection $AVANCE_ACTIVIDAD
 * @property Doctrine_Collection $AVANCE_ACTIVIDAD_2
 * @property Doctrine_Collection $VALOR_DATO_ACT
 * @property Doctrine_Collection $VALOR_DATO_ACT_3
 * 
 * @method integer             getIdacademico()          Returns the current record's "idacademico" value
 * @method integer             getIdactividad()          Returns the current record's "idactividad" value
 * @method string              getNombreactividad()      Returns the current record's "nombreactividad" value
 * @method string              getDescripcionactividad() Returns the current record's "descripcionactividad" value
 * @method string              getObservacionactividad() Returns the current record's "observacionactividad" value
 * @method integer             getIdtipoactividad()      Returns the current record's "idtipoactividad" value
 * @method integer             getIdestadoactividad()    Returns the current record's "idestadoactividad" value
 * @method ESTADO_ACTIVIDAD    getESTADOACTIVIDAD()      Returns the current record's "ESTADO_ACTIVIDAD" value
 * @method ACADEMICO           getACADEMICO()            Returns the current record's "ACADEMICO" value
 * @method TIPO_ACTIVIDAD      getTIPOACTIVIDAD()        Returns the current record's "TIPO_ACTIVIDAD" value
 * @method Doctrine_Collection getAVANCEACTIVIDAD()      Returns the current record's "AVANCE_ACTIVIDAD" collection
 * @method Doctrine_Collection getAVANCEACTIVIDAD2()     Returns the current record's "AVANCE_ACTIVIDAD_2" collection
 * @method Doctrine_Collection getVALORDATOACT()         Returns the current record's "VALOR_DATO_ACT" collection
 * @method Doctrine_Collection getVALORDATOACT3()        Returns the current record's "VALOR_DATO_ACT_3" collection
 * @method ACTIVIDAD           setIdacademico()          Sets the current record's "idacademico" value
 * @method ACTIVIDAD           setIdactividad()          Sets the current record's "idactividad" value
 * @method ACTIVIDAD           setNombreactividad()      Sets the current record's "nombreactividad" value
 * @method ACTIVIDAD           setDescripcionactividad() Sets the current record's "descripcionactividad" value
 * @method ACTIVIDAD           setObservacionactividad() Sets the current record's "observacionactividad" value
 * @method ACTIVIDAD           setIdtipoactividad()      Sets the current record's "idtipoactividad" value
 * @method ACTIVIDAD           setIdestadoactividad()    Sets the current record's "idestadoactividad" value
 * @method ACTIVIDAD           setESTADOACTIVIDAD()      Sets the current record's "ESTADO_ACTIVIDAD" value
 * @method ACTIVIDAD           setACADEMICO()            Sets the current record's "ACADEMICO" value
 * @method ACTIVIDAD           setTIPOACTIVIDAD()        Sets the current record's "TIPO_ACTIVIDAD" value
 * @method ACTIVIDAD           setAVANCEACTIVIDAD()      Sets the current record's "AVANCE_ACTIVIDAD" collection
 * @method ACTIVIDAD           setAVANCEACTIVIDAD2()     Sets the current record's "AVANCE_ACTIVIDAD_2" collection
 * @method ACTIVIDAD           setVALORDATOACT()         Sets the current record's "VALOR_DATO_ACT" collection
 * @method ACTIVIDAD           setVALORDATOACT3()        Sets the current record's "VALOR_DATO_ACT_3" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseACTIVIDAD extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ACTIVIDAD');
        $this->hasColumn('idacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idactividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombreactividad', 'string', 300, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 300,
             ));
        $this->hasColumn('descripcionactividad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('observacionactividad', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('idtipoactividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idestadoactividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ESTADO_ACTIVIDAD', array(
             'local' => 'idestadoactividad',
             'foreign' => 'idestadoactividad'));

        $this->hasOne('ACADEMICO', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasOne('TIPO_ACTIVIDAD', array(
             'local' => 'idtipoactividad',
             'foreign' => 'idtipoactividad'));

        $this->hasMany('AVANCE_ACTIVIDAD', array(
             'local' => 'idactividad',
             'foreign' => 'idactividad'));

        $this->hasMany('AVANCE_ACTIVIDAD as AVANCE_ACTIVIDAD_2', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasMany('VALOR_DATO_ACT', array(
             'local' => 'idactividad',
             'foreign' => 'idactividad'));

        $this->hasMany('VALOR_DATO_ACT as VALOR_DATO_ACT_3', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));
    }
}