<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DEPARTAMENTO', 'doctrine');

/**
 * BaseDEPARTAMENTO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iddepartamento
 * @property string $nombredepartamento
 * @property Doctrine_Collection $ACADEMICO
 * @property Doctrine_Collection $DIRECCION
 * 
 * @method integer             getIddepartamento()     Returns the current record's "iddepartamento" value
 * @method string              getNombredepartamento() Returns the current record's "nombredepartamento" value
 * @method Doctrine_Collection getACADEMICO()          Returns the current record's "ACADEMICO" collection
 * @method Doctrine_Collection getDIRECCION()          Returns the current record's "DIRECCION" collection
 * @method DEPARTAMENTO        setIddepartamento()     Sets the current record's "iddepartamento" value
 * @method DEPARTAMENTO        setNombredepartamento() Sets the current record's "nombredepartamento" value
 * @method DEPARTAMENTO        setACADEMICO()          Sets the current record's "ACADEMICO" collection
 * @method DEPARTAMENTO        setDIRECCION()          Sets the current record's "DIRECCION" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDEPARTAMENTO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('DEPARTAMENTO');
        $this->hasColumn('iddepartamento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombredepartamento', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ACADEMICO', array(
             'local' => 'iddepartamento',
             'foreign' => 'iddeptonac'));

        $this->hasMany('DIRECCION', array(
             'local' => 'iddepartamento',
             'foreign' => 'iddeptodir'));
    }
}