<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DIRECCION', 'doctrine');

/**
 * BaseDIRECCION
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iddireccion
 * @property string $contenidodir
 * @property integer $idciudaddir
 * @property integer $idacademico
 * @property ACADEMICO $ACADEMICO
 * @property CIUDAD $CIUDAD
 * 
 * @method integer   getIddireccion()  Returns the current record's "iddireccion" value
 * @method string    getContenidodir() Returns the current record's "contenidodir" value
 * @method integer   getIdciudaddir()  Returns the current record's "idciudaddir" value
 * @method integer   getIdacademico()  Returns the current record's "idacademico" value
 * @method ACADEMICO getACADEMICO()    Returns the current record's "ACADEMICO" value
 * @method CIUDAD    getCIUDAD()       Returns the current record's "CIUDAD" value
 * @method DIRECCION setIddireccion()  Sets the current record's "iddireccion" value
 * @method DIRECCION setContenidodir() Sets the current record's "contenidodir" value
 * @method DIRECCION setIdciudaddir()  Sets the current record's "idciudaddir" value
 * @method DIRECCION setIdacademico()  Sets the current record's "idacademico" value
 * @method DIRECCION setACADEMICO()    Sets the current record's "ACADEMICO" value
 * @method DIRECCION setCIUDAD()       Sets the current record's "CIUDAD" value
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDIRECCION extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('DIRECCION');
        $this->hasColumn('iddireccion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('contenidodir', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('idciudaddir', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ACADEMICO', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasOne('CIUDAD', array(
             'local' => 'idciudaddir',
             'foreign' => 'idciudad'));
    }
}