<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TIPO_CONTRATACION', 'doctrine');

/**
 * BaseTIPO_CONTRATACION
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipocontratacion
 * @property string $nombretipocontratacion
 * @property Doctrine_Collection $HISTORIAL_CARGO
 * 
 * @method integer             getIdtipocontratacion()     Returns the current record's "idtipocontratacion" value
 * @method string              getNombretipocontratacion() Returns the current record's "nombretipocontratacion" value
 * @method Doctrine_Collection getHISTORIALCARGO()         Returns the current record's "HISTORIAL_CARGO" collection
 * @method TIPO_CONTRATACION   setIdtipocontratacion()     Sets the current record's "idtipocontratacion" value
 * @method TIPO_CONTRATACION   setNombretipocontratacion() Sets the current record's "nombretipocontratacion" value
 * @method TIPO_CONTRATACION   setHISTORIALCARGO()         Sets the current record's "HISTORIAL_CARGO" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTIPO_CONTRATACION extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TIPO_CONTRATACION');
        $this->hasColumn('idtipocontratacion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombretipocontratacion', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('HISTORIAL_CARGO', array(
             'local' => 'idtipocontratacion',
             'foreign' => 'idtipocontratacion'));
    }
}