<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PERFIL', 'doctrine');

/**
 * BasePERFIL
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idperfil
 * @property string $nombreperfil
 * @property Doctrine_Collection $ACCIONXPERFIL
 * @property Doctrine_Collection $USUARIO
 * 
 * @method integer             getIdperfil()      Returns the current record's "idperfil" value
 * @method string              getNombreperfil()  Returns the current record's "nombreperfil" value
 * @method Doctrine_Collection getACCIONXPERFIL() Returns the current record's "ACCIONXPERFIL" collection
 * @method Doctrine_Collection getUSUARIO()       Returns the current record's "USUARIO" collection
 * @method PERFIL              setIdperfil()      Sets the current record's "idperfil" value
 * @method PERFIL              setNombreperfil()  Sets the current record's "nombreperfil" value
 * @method PERFIL              setACCIONXPERFIL() Sets the current record's "ACCIONXPERFIL" collection
 * @method PERFIL              setUSUARIO()       Sets the current record's "USUARIO" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePERFIL extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PERFIL');
        $this->hasColumn('idperfil', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombreperfil', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ACCIONXPERFIL', array(
             'local' => 'idperfil',
             'foreign' => 'idperfil'));

        $this->hasMany('USUARIO', array(
             'local' => 'idperfil',
             'foreign' => 'idperfil'));
    }
}