<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ACTXACT_UMA', 'doctrine');

/**
 * BaseACTXACT_UMA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idactividadumasup
 * @property integer $idactividaduma
 * @property ACTIVIDAD_UMA $ACTIVIDAD_UMA
 * @property ACTIVIDAD_UMA $ACTIVIDAD_UMA_2
 * 
 * @method integer       getIdactividadumasup() Returns the current record's "idactividadumasup" value
 * @method integer       getIdactividaduma()    Returns the current record's "idactividaduma" value
 * @method ACTIVIDAD_UMA getACTIVIDADUMA()      Returns the current record's "ACTIVIDAD_UMA" value
 * @method ACTIVIDAD_UMA getACTIVIDADUMA2()     Returns the current record's "ACTIVIDAD_UMA_2" value
 * @method ACTXACT_UMA   setIdactividadumasup() Sets the current record's "idactividadumasup" value
 * @method ACTXACT_UMA   setIdactividaduma()    Sets the current record's "idactividaduma" value
 * @method ACTXACT_UMA   setACTIVIDADUMA()      Sets the current record's "ACTIVIDAD_UMA" value
 * @method ACTXACT_UMA   setACTIVIDADUMA2()     Sets the current record's "ACTIVIDAD_UMA_2" value
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseACTXACT_UMA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ACTXACT_UMA');
        $this->hasColumn('idactividadumasup', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idactividaduma', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ACTIVIDAD_UMA', array(
             'local' => 'idactividaduma',
             'foreign' => 'idactividaduma'));

        $this->hasOne('ACTIVIDAD_UMA as ACTIVIDAD_UMA_2', array(
             'local' => 'idactividadumasup',
             'foreign' => 'idactividaduma'));
    }
}