<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ESTADO_ACTIVIDAD', 'doctrine');

/**
 * BaseESTADO_ACTIVIDAD
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idestadoactividad
 * @property string $nombreestadoactividad
 * @property integer $permiteedicion
 * @property integer $esestadoinicial
 * @property Doctrine_Collection $ACTIVIDAD
 * 
 * @method integer             getIdestadoactividad()     Returns the current record's "idestadoactividad" value
 * @method string              getNombreestadoactividad() Returns the current record's "nombreestadoactividad" value
 * @method integer             getPermiteedicion()        Returns the current record's "permiteedicion" value
 * @method integer             getEsestadoinicial()       Returns the current record's "esestadoinicial" value
 * @method Doctrine_Collection getACTIVIDAD()             Returns the current record's "ACTIVIDAD" collection
 * @method ESTADO_ACTIVIDAD    setIdestadoactividad()     Sets the current record's "idestadoactividad" value
 * @method ESTADO_ACTIVIDAD    setNombreestadoactividad() Sets the current record's "nombreestadoactividad" value
 * @method ESTADO_ACTIVIDAD    setPermiteedicion()        Sets the current record's "permiteedicion" value
 * @method ESTADO_ACTIVIDAD    setEsestadoinicial()       Sets the current record's "esestadoinicial" value
 * @method ESTADO_ACTIVIDAD    setACTIVIDAD()             Sets the current record's "ACTIVIDAD" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseESTADO_ACTIVIDAD extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ESTADO_ACTIVIDAD');
        $this->hasColumn('idestadoactividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombreestadoactividad', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('permiteedicion', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('esestadoinicial', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ACTIVIDAD', array(
             'local' => 'idestadoactividad',
             'foreign' => 'idestadoactividad'));
    }
}