<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('USUARIO', 'doctrine');

/**
 * BaseUSUARIO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idusuario
 * @property string $nombreusuario
 * @property string $contraseniausuario
 * @property integer $idperfil
 * @property PERFIL $PERFIL
 * @property Doctrine_Collection $ACADEMICO
 * 
 * @method integer             getIdusuario()          Returns the current record's "idusuario" value
 * @method string              getNombreusuario()      Returns the current record's "nombreusuario" value
 * @method string              getContraseniausuario() Returns the current record's "contraseniausuario" value
 * @method integer             getIdperfil()           Returns the current record's "idperfil" value
 * @method PERFIL              getPERFIL()             Returns the current record's "PERFIL" value
 * @method Doctrine_Collection getACADEMICO()          Returns the current record's "ACADEMICO" collection
 * @method USUARIO             setIdusuario()          Sets the current record's "idusuario" value
 * @method USUARIO             setNombreusuario()      Sets the current record's "nombreusuario" value
 * @method USUARIO             setContraseniausuario() Sets the current record's "contraseniausuario" value
 * @method USUARIO             setIdperfil()           Sets the current record's "idperfil" value
 * @method USUARIO             setPERFIL()             Sets the current record's "PERFIL" value
 * @method USUARIO             setACADEMICO()          Sets the current record's "ACADEMICO" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUSUARIO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('USUARIO');
        $this->hasColumn('idusuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombreusuario', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('contraseniausuario', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('idperfil', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PERFIL', array(
             'local' => 'idperfil',
             'foreign' => 'idperfil'));

        $this->hasMany('ACADEMICO', array(
             'local' => 'idusuario',
             'foreign' => 'idusuario'));
    }
}