<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TIPO_ACTIVIDAD', 'doctrine');

/**
 * BaseTIPO_ACTIVIDAD
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipoactividad
 * @property string $nombretipoactividad
 * @property integer $esrequeridoarchivo
 * @property Doctrine_Collection $ACTIVIDAD
 * @property Doctrine_Collection $TIPOXDATO_ACT
 * 
 * @method integer             getIdtipoactividad()     Returns the current record's "idtipoactividad" value
 * @method string              getNombretipoactividad() Returns the current record's "nombretipoactividad" value
 * @method integer             getEsrequeridoarchivo()  Returns the current record's "esrequeridoarchivo" value
 * @method Doctrine_Collection getACTIVIDAD()           Returns the current record's "ACTIVIDAD" collection
 * @method Doctrine_Collection getTIPOXDATOACT()        Returns the current record's "TIPOXDATO_ACT" collection
 * @method TIPO_ACTIVIDAD      setIdtipoactividad()     Sets the current record's "idtipoactividad" value
 * @method TIPO_ACTIVIDAD      setNombretipoactividad() Sets the current record's "nombretipoactividad" value
 * @method TIPO_ACTIVIDAD      setEsrequeridoarchivo()  Sets the current record's "esrequeridoarchivo" value
 * @method TIPO_ACTIVIDAD      setACTIVIDAD()           Sets the current record's "ACTIVIDAD" collection
 * @method TIPO_ACTIVIDAD      setTIPOXDATOACT()        Sets the current record's "TIPOXDATO_ACT" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTIPO_ACTIVIDAD extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TIPO_ACTIVIDAD');
        $this->hasColumn('idtipoactividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombretipoactividad', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('esrequeridoarchivo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ACTIVIDAD', array(
             'local' => 'idtipoactividad',
             'foreign' => 'idtipoactividad'));

        $this->hasMany('TIPOXDATO_ACT', array(
             'local' => 'idtipoactividad',
             'foreign' => 'idtipoactividad'));
    }
}