<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VALOR_DATO_ACT', 'doctrine');

/**
 * BaseVALOR_DATO_ACT
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idacademico
 * @property integer $idactividad
 * @property integer $iddatoactividad
 * @property integer $valorbooleanact
 * @property integer $valorenteroact
 * @property integer $valorrealact
 * @property date $valorfechaact
 * @property string $valorcadenaact
 * @property integer $idopciondatoact
 * @property OPCION_DATO_ACT $OPCION_DATO_ACT
 * @property ACTIVIDAD $ACTIVIDAD
 * @property ACTIVIDAD $ACTIVIDAD_3
 * @property DATO_ACTIVIDAD $DATO_ACTIVIDAD
 * 
 * @method integer         getIdacademico()     Returns the current record's "idacademico" value
 * @method integer         getIdactividad()     Returns the current record's "idactividad" value
 * @method integer         getIddatoactividad() Returns the current record's "iddatoactividad" value
 * @method integer         getValorbooleanact() Returns the current record's "valorbooleanact" value
 * @method integer         getValorenteroact()  Returns the current record's "valorenteroact" value
 * @method integer         getValorrealact()    Returns the current record's "valorrealact" value
 * @method date            getValorfechaact()   Returns the current record's "valorfechaact" value
 * @method string          getValorcadenaact()  Returns the current record's "valorcadenaact" value
 * @method integer         getIdopciondatoact() Returns the current record's "idopciondatoact" value
 * @method OPCION_DATO_ACT getOPCIONDATOACT()   Returns the current record's "OPCION_DATO_ACT" value
 * @method ACTIVIDAD       getACTIVIDAD()       Returns the current record's "ACTIVIDAD" value
 * @method ACTIVIDAD       getACTIVIDAD3()      Returns the current record's "ACTIVIDAD_3" value
 * @method DATO_ACTIVIDAD  getDATOACTIVIDAD()   Returns the current record's "DATO_ACTIVIDAD" value
 * @method VALOR_DATO_ACT  setIdacademico()     Sets the current record's "idacademico" value
 * @method VALOR_DATO_ACT  setIdactividad()     Sets the current record's "idactividad" value
 * @method VALOR_DATO_ACT  setIddatoactividad() Sets the current record's "iddatoactividad" value
 * @method VALOR_DATO_ACT  setValorbooleanact() Sets the current record's "valorbooleanact" value
 * @method VALOR_DATO_ACT  setValorenteroact()  Sets the current record's "valorenteroact" value
 * @method VALOR_DATO_ACT  setValorrealact()    Sets the current record's "valorrealact" value
 * @method VALOR_DATO_ACT  setValorfechaact()   Sets the current record's "valorfechaact" value
 * @method VALOR_DATO_ACT  setValorcadenaact()  Sets the current record's "valorcadenaact" value
 * @method VALOR_DATO_ACT  setIdopciondatoact() Sets the current record's "idopciondatoact" value
 * @method VALOR_DATO_ACT  setOPCIONDATOACT()   Sets the current record's "OPCION_DATO_ACT" value
 * @method VALOR_DATO_ACT  setACTIVIDAD()       Sets the current record's "ACTIVIDAD" value
 * @method VALOR_DATO_ACT  setACTIVIDAD3()      Sets the current record's "ACTIVIDAD_3" value
 * @method VALOR_DATO_ACT  setDATOACTIVIDAD()   Sets the current record's "DATO_ACTIVIDAD" value
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVALOR_DATO_ACT extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('VALOR_DATO_ACT');
        $this->hasColumn('idacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idactividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('iddatoactividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('valorbooleanact', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('valorenteroact', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('valorrealact', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('valorfechaact', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('valorcadenaact', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('idopciondatoact', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('OPCION_DATO_ACT', array(
             'local' => 'idopciondatoact',
             'foreign' => 'idopciondatoact'));

        $this->hasOne('ACTIVIDAD', array(
             'local' => 'idactividad',
             'foreign' => 'idactividad'));

        $this->hasOne('ACTIVIDAD as ACTIVIDAD_3', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasOne('DATO_ACTIVIDAD', array(
             'local' => 'iddatoactividad',
             'foreign' => 'iddatoactividad'));
    }
}