<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TIPOXDATO_ACT', 'doctrine');

/**
 * BaseTIPOXDATO_ACT
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtipoactividad
 * @property integer $iddatoactividad
 * @property DATO_ACTIVIDAD $DATO_ACTIVIDAD
 * @property TIPO_ACTIVIDAD $TIPO_ACTIVIDAD
 * 
 * @method integer        getIdtipoactividad() Returns the current record's "idtipoactividad" value
 * @method integer        getIddatoactividad() Returns the current record's "iddatoactividad" value
 * @method DATO_ACTIVIDAD getDATOACTIVIDAD()   Returns the current record's "DATO_ACTIVIDAD" value
 * @method TIPO_ACTIVIDAD getTIPOACTIVIDAD()   Returns the current record's "TIPO_ACTIVIDAD" value
 * @method TIPOXDATO_ACT  setIdtipoactividad() Sets the current record's "idtipoactividad" value
 * @method TIPOXDATO_ACT  setIddatoactividad() Sets the current record's "iddatoactividad" value
 * @method TIPOXDATO_ACT  setDATOACTIVIDAD()   Sets the current record's "DATO_ACTIVIDAD" value
 * @method TIPOXDATO_ACT  setTIPOACTIVIDAD()   Sets the current record's "TIPO_ACTIVIDAD" value
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTIPOXDATO_ACT extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TIPOXDATO_ACT');
        $this->hasColumn('idtipoactividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('iddatoactividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DATO_ACTIVIDAD', array(
             'local' => 'iddatoactividad',
             'foreign' => 'iddatoactividad'));

        $this->hasOne('TIPO_ACTIVIDAD', array(
             'local' => 'idtipoactividad',
             'foreign' => 'idtipoactividad'));
    }
}