<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DIRECCION', 'doctrine');

/**
 * BaseDIRECCION
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idacademico
 * @property integer $iddireccion
 * @property string $contenidodir
 * @property integer $idpaisdir
 * @property integer $idestadodir
 * @property integer $idciudaddir
 * @property CIUDAD $CIUDAD
 * @property CIUDAD $CIUDAD_2
 * @property CIUDAD $CIUDAD_3
 * @property ACADEMICO $ACADEMICO
 * 
 * @method integer   getIdacademico()  Returns the current record's "idacademico" value
 * @method integer   getIddireccion()  Returns the current record's "iddireccion" value
 * @method string    getContenidodir() Returns the current record's "contenidodir" value
 * @method integer   getIdpaisdir()    Returns the current record's "idpaisdir" value
 * @method integer   getIdestadodir()  Returns the current record's "idestadodir" value
 * @method integer   getIdciudaddir()  Returns the current record's "idciudaddir" value
 * @method CIUDAD    getCIUDAD()       Returns the current record's "CIUDAD" value
 * @method CIUDAD    getCIUDAD2()      Returns the current record's "CIUDAD_2" value
 * @method CIUDAD    getCIUDAD3()      Returns the current record's "CIUDAD_3" value
 * @method ACADEMICO getACADEMICO()    Returns the current record's "ACADEMICO" value
 * @method DIRECCION setIdacademico()  Sets the current record's "idacademico" value
 * @method DIRECCION setIddireccion()  Sets the current record's "iddireccion" value
 * @method DIRECCION setContenidodir() Sets the current record's "contenidodir" value
 * @method DIRECCION setIdpaisdir()    Sets the current record's "idpaisdir" value
 * @method DIRECCION setIdestadodir()  Sets the current record's "idestadodir" value
 * @method DIRECCION setIdciudaddir()  Sets the current record's "idciudaddir" value
 * @method DIRECCION setCIUDAD()       Sets the current record's "CIUDAD" value
 * @method DIRECCION setCIUDAD2()      Sets the current record's "CIUDAD_2" value
 * @method DIRECCION setCIUDAD3()      Sets the current record's "CIUDAD_3" value
 * @method DIRECCION setACADEMICO()    Sets the current record's "ACADEMICO" value
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDIRECCION extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('DIRECCION');
        $this->hasColumn('idacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('iddireccion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('contenidodir', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('idpaisdir', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idestadodir', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idciudaddir', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CIUDAD', array(
             'local' => 'idciudaddir',
             'foreign' => 'idciudad'));

        $this->hasOne('CIUDAD as CIUDAD_2', array(
             'local' => 'idestadodir',
             'foreign' => 'idestado'));

        $this->hasOne('CIUDAD as CIUDAD_3', array(
             'local' => 'idpaisdir',
             'foreign' => 'idpais'));

        $this->hasOne('ACADEMICO', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));
    }
}