<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TEL_ACADEMICO', 'doctrine');

/**
 * BaseTEL_ACADEMICO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idacademico
 * @property integer $idtelacademico
 * @property string $numtelacademico
 * @property integer $tipotelacademico
 * @property ACADEMICO $ACADEMICO
 * 
 * @method integer       getIdacademico()      Returns the current record's "idacademico" value
 * @method integer       getIdtelacademico()   Returns the current record's "idtelacademico" value
 * @method string        getNumtelacademico()  Returns the current record's "numtelacademico" value
 * @method integer       getTipotelacademico() Returns the current record's "tipotelacademico" value
 * @method ACADEMICO     getACADEMICO()        Returns the current record's "ACADEMICO" value
 * @method TEL_ACADEMICO setIdacademico()      Sets the current record's "idacademico" value
 * @method TEL_ACADEMICO setIdtelacademico()   Sets the current record's "idtelacademico" value
 * @method TEL_ACADEMICO setNumtelacademico()  Sets the current record's "numtelacademico" value
 * @method TEL_ACADEMICO setTipotelacademico() Sets the current record's "tipotelacademico" value
 * @method TEL_ACADEMICO setACADEMICO()        Sets the current record's "ACADEMICO" value
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTEL_ACADEMICO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TEL_ACADEMICO');
        $this->hasColumn('idacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idtelacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('numtelacademico', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tipotelacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ACADEMICO', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));
    }
}