<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ACCIONXPERFIL', 'doctrine');

/**
 * BaseACCIONXPERFIL
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idmodulo
 * @property integer $idaccion
 * @property integer $idperfil
 * @property PERFIL $PERFIL
 * @property ACCION $ACCION
 * @property ACCION $ACCION_3
 * 
 * @method integer       getIdmodulo() Returns the current record's "idmodulo" value
 * @method integer       getIdaccion() Returns the current record's "idaccion" value
 * @method integer       getIdperfil() Returns the current record's "idperfil" value
 * @method PERFIL        getPERFIL()   Returns the current record's "PERFIL" value
 * @method ACCION        getACCION()   Returns the current record's "ACCION" value
 * @method ACCION        getACCION3()  Returns the current record's "ACCION_3" value
 * @method ACCIONXPERFIL setIdmodulo() Sets the current record's "idmodulo" value
 * @method ACCIONXPERFIL setIdaccion() Sets the current record's "idaccion" value
 * @method ACCIONXPERFIL setIdperfil() Sets the current record's "idperfil" value
 * @method ACCIONXPERFIL setPERFIL()   Sets the current record's "PERFIL" value
 * @method ACCIONXPERFIL setACCION()   Sets the current record's "ACCION" value
 * @method ACCIONXPERFIL setACCION3()  Sets the current record's "ACCION_3" value
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseACCIONXPERFIL extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ACCIONXPERFIL');
        $this->hasColumn('idmodulo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idaccion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idperfil', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PERFIL', array(
             'local' => 'idperfil',
             'foreign' => 'idperfil'));

        $this->hasOne('ACCION', array(
             'local' => 'idaccion',
             'foreign' => 'idaccion'));

        $this->hasOne('ACCION as ACCION_3', array(
             'local' => 'idmodulo',
             'foreign' => 'idmodulo'));
    }
}