<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TITULO_ACADEMICO', 'doctrine');

/**
 * BaseTITULO_ACADEMICO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtituloacademico
 * @property string $nombretituloacademico
 * @property Doctrine_Collection $HISTORIAL_GRADO_ACAD
 * 
 * @method integer             getIdtituloacademico()     Returns the current record's "idtituloacademico" value
 * @method string              getNombretituloacademico() Returns the current record's "nombretituloacademico" value
 * @method Doctrine_Collection getHISTORIALGRADOACAD()    Returns the current record's "HISTORIAL_GRADO_ACAD" collection
 * @method TITULO_ACADEMICO    setIdtituloacademico()     Sets the current record's "idtituloacademico" value
 * @method TITULO_ACADEMICO    setNombretituloacademico() Sets the current record's "nombretituloacademico" value
 * @method TITULO_ACADEMICO    setHISTORIALGRADOACAD()    Sets the current record's "HISTORIAL_GRADO_ACAD" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTITULO_ACADEMICO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('TITULO_ACADEMICO');
        $this->hasColumn('idtituloacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombretituloacademico', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('HISTORIAL_GRADO_ACAD', array(
             'local' => 'idtituloacademico',
             'foreign' => 'idtituloacademico'));
    }
}