<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HISTORIAL_GRADO_ACAD', 'doctrine');

/**
 * BaseHISTORIAL_GRADO_ACAD
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idhistorialgradoacad
 * @property integer $anioobtencion
 * @property integer $idacademico
 * @property integer $idnivelestudio
 * @property integer $idtituloacademico
 * @property TITULO_ACADEMICO $TITULO_ACADEMICO
 * @property ACADEMICO $ACADEMICO
 * @property NIVEL_ESTUDIO $NIVEL_ESTUDIO
 * 
 * @method integer              getIdhistorialgradoacad() Returns the current record's "idhistorialgradoacad" value
 * @method integer              getAnioobtencion()        Returns the current record's "anioobtencion" value
 * @method integer              getIdacademico()          Returns the current record's "idacademico" value
 * @method integer              getIdnivelestudio()       Returns the current record's "idnivelestudio" value
 * @method integer              getIdtituloacademico()    Returns the current record's "idtituloacademico" value
 * @method TITULO_ACADEMICO     getTITULOACADEMICO()      Returns the current record's "TITULO_ACADEMICO" value
 * @method ACADEMICO            getACADEMICO()            Returns the current record's "ACADEMICO" value
 * @method NIVEL_ESTUDIO        getNIVELESTUDIO()         Returns the current record's "NIVEL_ESTUDIO" value
 * @method HISTORIAL_GRADO_ACAD setIdhistorialgradoacad() Sets the current record's "idhistorialgradoacad" value
 * @method HISTORIAL_GRADO_ACAD setAnioobtencion()        Sets the current record's "anioobtencion" value
 * @method HISTORIAL_GRADO_ACAD setIdacademico()          Sets the current record's "idacademico" value
 * @method HISTORIAL_GRADO_ACAD setIdnivelestudio()       Sets the current record's "idnivelestudio" value
 * @method HISTORIAL_GRADO_ACAD setIdtituloacademico()    Sets the current record's "idtituloacademico" value
 * @method HISTORIAL_GRADO_ACAD setTITULOACADEMICO()      Sets the current record's "TITULO_ACADEMICO" value
 * @method HISTORIAL_GRADO_ACAD setACADEMICO()            Sets the current record's "ACADEMICO" value
 * @method HISTORIAL_GRADO_ACAD setNIVELESTUDIO()         Sets the current record's "NIVEL_ESTUDIO" value
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHISTORIAL_GRADO_ACAD extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('HISTORIAL_GRADO_ACAD');
        $this->hasColumn('idhistorialgradoacad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('anioobtencion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idnivelestudio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idtituloacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TITULO_ACADEMICO', array(
             'local' => 'idtituloacademico',
             'foreign' => 'idtituloacademico'));

        $this->hasOne('ACADEMICO', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));

        $this->hasOne('NIVEL_ESTUDIO', array(
             'local' => 'idnivelestudio',
             'foreign' => 'idnivelestudio'));
    }
}