<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PAIS', 'doctrine');

/**
 * BasePAIS
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idpais
 * @property string $codigoisopais
 * @property string $nombreisopais
 * @property Doctrine_Collection $ACADEMICO
 * @property Doctrine_Collection $ACADEMICO_7
 * @property Doctrine_Collection $DIRECCION
 * 
 * @method integer             getIdpais()        Returns the current record's "idpais" value
 * @method string              getCodigoisopais() Returns the current record's "codigoisopais" value
 * @method string              getNombreisopais() Returns the current record's "nombreisopais" value
 * @method Doctrine_Collection getACADEMICO()     Returns the current record's "ACADEMICO" collection
 * @method Doctrine_Collection getACADEMICO7()    Returns the current record's "ACADEMICO_7" collection
 * @method Doctrine_Collection getDIRECCION()     Returns the current record's "DIRECCION" collection
 * @method PAIS                setIdpais()        Sets the current record's "idpais" value
 * @method PAIS                setCodigoisopais() Sets the current record's "codigoisopais" value
 * @method PAIS                setNombreisopais() Sets the current record's "nombreisopais" value
 * @method PAIS                setACADEMICO()     Sets the current record's "ACADEMICO" collection
 * @method PAIS                setACADEMICO7()    Sets the current record's "ACADEMICO_7" collection
 * @method PAIS                setDIRECCION()     Sets the current record's "DIRECCION" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePAIS extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('PAIS');
        $this->hasColumn('idpais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigoisopais', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('nombreisopais', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ACADEMICO', array(
             'local' => 'idpais',
             'foreign' => 'idpaisnac'));

        $this->hasMany('ACADEMICO as ACADEMICO_7', array(
             'local' => 'idpais',
             'foreign' => 'idpaisciudadania'));

        $this->hasMany('DIRECCION', array(
             'local' => 'idpais',
             'foreign' => 'idpaisdir'));
    }
}