<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ACTIVIDAD_UMA', 'doctrine');

/**
 * BaseACTIVIDAD_UMA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idactividaduma
 * @property string $nombreactividaduma
 * @property string $descripcionactividaduma
 * @property decimal $cantidadumadef
 * @property integer $idcategoriauma
 * @property CATEGORIA_UMA $CATEGORIA_UMA
 * @property Doctrine_Collection $ACTXACT_UMA
 * @property Doctrine_Collection $ACTXACT_UMA_2
 * 
 * @method integer             getIdactividaduma()          Returns the current record's "idactividaduma" value
 * @method string              getNombreactividaduma()      Returns the current record's "nombreactividaduma" value
 * @method string              getDescripcionactividaduma() Returns the current record's "descripcionactividaduma" value
 * @method decimal             getCantidadumadef()          Returns the current record's "cantidadumadef" value
 * @method integer             getIdcategoriauma()          Returns the current record's "idcategoriauma" value
 * @method CATEGORIA_UMA       getCATEGORIAUMA()            Returns the current record's "CATEGORIA_UMA" value
 * @method Doctrine_Collection getACTXACTUMA()              Returns the current record's "ACTXACT_UMA" collection
 * @method Doctrine_Collection getACTXACTUMA2()             Returns the current record's "ACTXACT_UMA_2" collection
 * @method ACTIVIDAD_UMA       setIdactividaduma()          Sets the current record's "idactividaduma" value
 * @method ACTIVIDAD_UMA       setNombreactividaduma()      Sets the current record's "nombreactividaduma" value
 * @method ACTIVIDAD_UMA       setDescripcionactividaduma() Sets the current record's "descripcionactividaduma" value
 * @method ACTIVIDAD_UMA       setCantidadumadef()          Sets the current record's "cantidadumadef" value
 * @method ACTIVIDAD_UMA       setIdcategoriauma()          Sets the current record's "idcategoriauma" value
 * @method ACTIVIDAD_UMA       setCATEGORIAUMA()            Sets the current record's "CATEGORIA_UMA" value
 * @method ACTIVIDAD_UMA       setACTXACTUMA()              Sets the current record's "ACTXACT_UMA" collection
 * @method ACTIVIDAD_UMA       setACTXACTUMA2()             Sets the current record's "ACTXACT_UMA_2" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseACTIVIDAD_UMA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ACTIVIDAD_UMA');
        $this->hasColumn('idactividaduma', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombreactividaduma', 'string', 300, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 300,
             ));
        $this->hasColumn('descripcionactividaduma', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('cantidadumadef', 'decimal', 2, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('idcategoriauma', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CATEGORIA_UMA', array(
             'local' => 'idcategoriauma',
             'foreign' => 'idcategoriauma'));

        $this->hasMany('ACTXACT_UMA', array(
             'local' => 'idactividaduma',
             'foreign' => 'idactividaduma'));

        $this->hasMany('ACTXACT_UMA as ACTXACT_UMA_2', array(
             'local' => 'idactividaduma',
             'foreign' => 'idactividadumasup'));
    }
}