<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ESTADO', 'doctrine');

/**
 * BaseESTADO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idpais
 * @property integer $idestado
 * @property string $nombreestado
 * @property PAIS $PAIS
 * @property Doctrine_Collection $CIUDAD
 * @property Doctrine_Collection $CIUDAD_2
 * 
 * @method integer             getIdpais()       Returns the current record's "idpais" value
 * @method integer             getIdestado()     Returns the current record's "idestado" value
 * @method string              getNombreestado() Returns the current record's "nombreestado" value
 * @method PAIS                getPAIS()         Returns the current record's "PAIS" value
 * @method Doctrine_Collection getCIUDAD()       Returns the current record's "CIUDAD" collection
 * @method Doctrine_Collection getCIUDAD2()      Returns the current record's "CIUDAD_2" collection
 * @method ESTADO              setIdpais()       Sets the current record's "idpais" value
 * @method ESTADO              setIdestado()     Sets the current record's "idestado" value
 * @method ESTADO              setNombreestado() Sets the current record's "nombreestado" value
 * @method ESTADO              setPAIS()         Sets the current record's "PAIS" value
 * @method ESTADO              setCIUDAD()       Sets the current record's "CIUDAD" collection
 * @method ESTADO              setCIUDAD2()      Sets the current record's "CIUDAD_2" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseESTADO extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ESTADO');
        $this->hasColumn('idpais', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idestado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombreestado', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PAIS', array(
             'local' => 'idpais',
             'foreign' => 'idpais'));

        $this->hasMany('CIUDAD', array(
             'local' => 'idestado',
             'foreign' => 'idestado'));

        $this->hasMany('CIUDAD as CIUDAD_2', array(
             'local' => 'idpais',
             'foreign' => 'idpais'));
    }
}