<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AVANCE_ACTIVIDAD', 'doctrine');

/**
 * BaseAVANCE_ACTIVIDAD
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idacademico
 * @property integer $idactividad
 * @property integer $idavanceact
 * @property date $fechainicioav
 * @property date $fechafinav
 * @property date $fechareporteav
 * @property decimal $porcentajeav
 * @property ACTIVIDAD $ACTIVIDAD
 * @property ACTIVIDAD $ACTIVIDAD_2
 * 
 * @method integer          getIdacademico()    Returns the current record's "idacademico" value
 * @method integer          getIdactividad()    Returns the current record's "idactividad" value
 * @method integer          getIdavanceact()    Returns the current record's "idavanceact" value
 * @method date             getFechainicioav()  Returns the current record's "fechainicioav" value
 * @method date             getFechafinav()     Returns the current record's "fechafinav" value
 * @method date             getFechareporteav() Returns the current record's "fechareporteav" value
 * @method decimal          getPorcentajeav()   Returns the current record's "porcentajeav" value
 * @method ACTIVIDAD        getACTIVIDAD()      Returns the current record's "ACTIVIDAD" value
 * @method ACTIVIDAD        getACTIVIDAD2()     Returns the current record's "ACTIVIDAD_2" value
 * @method AVANCE_ACTIVIDAD setIdacademico()    Sets the current record's "idacademico" value
 * @method AVANCE_ACTIVIDAD setIdactividad()    Sets the current record's "idactividad" value
 * @method AVANCE_ACTIVIDAD setIdavanceact()    Sets the current record's "idavanceact" value
 * @method AVANCE_ACTIVIDAD setFechainicioav()  Sets the current record's "fechainicioav" value
 * @method AVANCE_ACTIVIDAD setFechafinav()     Sets the current record's "fechafinav" value
 * @method AVANCE_ACTIVIDAD setFechareporteav() Sets the current record's "fechareporteav" value
 * @method AVANCE_ACTIVIDAD setPorcentajeav()   Sets the current record's "porcentajeav" value
 * @method AVANCE_ACTIVIDAD setACTIVIDAD()      Sets the current record's "ACTIVIDAD" value
 * @method AVANCE_ACTIVIDAD setACTIVIDAD2()     Sets the current record's "ACTIVIDAD_2" value
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAVANCE_ACTIVIDAD extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('AVANCE_ACTIVIDAD');
        $this->hasColumn('idacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idactividad', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idavanceact', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fechainicioav', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fechafinav', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fechareporteav', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('porcentajeav', 'decimal', 2, array(
             'type' => 'decimal',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ACTIVIDAD', array(
             'local' => 'idactividad',
             'foreign' => 'idactividad'));

        $this->hasOne('ACTIVIDAD as ACTIVIDAD_2', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));
    }
}