<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UNIDAD_ORGANIZATIVA', 'doctrine');

/**
 * BaseUNIDAD_ORGANIZATIVA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idunidadorganizativa
 * @property string $nombreunidadorganizativa
 * @property integer $esdepartamento
 * @property Doctrine_Collection $CARGOXUNIDAD_ORG
 * @property Doctrine_Collection $MATERIA
 * 
 * @method integer             getIdunidadorganizativa()     Returns the current record's "idunidadorganizativa" value
 * @method string              getNombreunidadorganizativa() Returns the current record's "nombreunidadorganizativa" value
 * @method integer             getEsdepartamento()           Returns the current record's "esdepartamento" value
 * @method Doctrine_Collection getCARGOXUNIDADORG()          Returns the current record's "CARGOXUNIDAD_ORG" collection
 * @method Doctrine_Collection getMATERIA()                  Returns the current record's "MATERIA" collection
 * @method UNIDAD_ORGANIZATIVA setIdunidadorganizativa()     Sets the current record's "idunidadorganizativa" value
 * @method UNIDAD_ORGANIZATIVA setNombreunidadorganizativa() Sets the current record's "nombreunidadorganizativa" value
 * @method UNIDAD_ORGANIZATIVA setEsdepartamento()           Sets the current record's "esdepartamento" value
 * @method UNIDAD_ORGANIZATIVA setCARGOXUNIDADORG()          Sets the current record's "CARGOXUNIDAD_ORG" collection
 * @method UNIDAD_ORGANIZATIVA setMATERIA()                  Sets the current record's "MATERIA" collection
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUNIDAD_ORGANIZATIVA extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('UNIDAD_ORGANIZATIVA');
        $this->hasColumn('idunidadorganizativa', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombreunidadorganizativa', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('esdepartamento', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CARGOXUNIDAD_ORG', array(
             'local' => 'idunidadorganizativa',
             'foreign' => 'idunidadorganizativa'));

        $this->hasMany('MATERIA', array(
             'local' => 'idunidadorganizativa',
             'foreign' => 'idunidadorganizativa'));
    }
}