<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CONTACTO_EMER', 'doctrine');

/**
 * BaseCONTACTO_EMER
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idacademico
 * @property integer $idcontactoemer
 * @property string $nombrecontactoemer
 * @property string $numtelcontactoemer
 * @property integer $tipotelcontactoemer
 * @property ACADEMICO $ACADEMICO
 * 
 * @method integer       getIdacademico()         Returns the current record's "idacademico" value
 * @method integer       getIdcontactoemer()      Returns the current record's "idcontactoemer" value
 * @method string        getNombrecontactoemer()  Returns the current record's "nombrecontactoemer" value
 * @method string        getNumtelcontactoemer()  Returns the current record's "numtelcontactoemer" value
 * @method integer       getTipotelcontactoemer() Returns the current record's "tipotelcontactoemer" value
 * @method ACADEMICO     getACADEMICO()           Returns the current record's "ACADEMICO" value
 * @method CONTACTO_EMER setIdacademico()         Sets the current record's "idacademico" value
 * @method CONTACTO_EMER setIdcontactoemer()      Sets the current record's "idcontactoemer" value
 * @method CONTACTO_EMER setNombrecontactoemer()  Sets the current record's "nombrecontactoemer" value
 * @method CONTACTO_EMER setNumtelcontactoemer()  Sets the current record's "numtelcontactoemer" value
 * @method CONTACTO_EMER setTipotelcontactoemer() Sets the current record's "tipotelcontactoemer" value
 * @method CONTACTO_EMER setACADEMICO()           Sets the current record's "ACADEMICO" value
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCONTACTO_EMER extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CONTACTO_EMER');
        $this->hasColumn('idacademico', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idcontactoemer', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombrecontactoemer', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('numtelcontactoemer', 'string', 25, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('tipotelcontactoemer', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ACADEMICO', array(
             'local' => 'idacademico',
             'foreign' => 'idacademico'));
    }
}