<?php

/**
 * ACADEMICO
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ACADEMICO extends BaseACADEMICO
{
    public static $strSexos = array(0 => 'Masculino', 1 => 'Femenino');
    
    public function getSexoacad_Texto() {
        return self::$strSexos[parent::getSexoacad()];
    }
    
    public function getEsescalafonado_Texto() {
        return Util::obtenertextoBooleano(parent::getEsescalafonado());
    }
    
    public function getEspensionado_Texto() {
        return Util::obtenertextoBooleano(parent::getEspensionado());
    }

    public function getUsalentes_Texto() {
        return Util::obtenertextoBooleano(parent::getUsalentes());
    }
    
    public function getFechanacimientoacad_Texto() {
        return $this->getDateTimeObject('fechanacimientoacad')->format('d/m/Y');
    }

    public function obtenerDato($strCampo)
    {
        $strValor = '';
        switch($strCampo)
        {
            case 'apellidonombre':
                $strValor = $this->getPrimerapellidoacad().', '.$this->getPrimernombreacad();
                break;
            case 'codigo':
                $strValor = $this->getCodigoacademico();
                break;
        }
        return $strValor;
    }
    
    public static function obtenerAcademicoPorIdUsuario($idUsuario)
    {
        $query = Doctrine_Query::create()->from('ACADEMICO acd')
                    ->where('acd.idUsuario = ?', $idUsuario);
        return $query->fetchOne();
    }
}
