<?php

/**
 * ACADEMICOXIDIOMATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ACADEMICOXIDIOMATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ACADEMICOXIDIOMATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ACADEMICOXIDIOMA');
    }
}