<?php

/**
 * ACADEMICOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ACADEMICOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ACADEMICOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ACADEMICO');
    }
    
    public function obtenerConsultaAcademicos()
    {
        return Doctrine_Query::create()
                ->select('a.codigoacademico, a.primernombreacad, a.primerapellidoacad')
                ->from('ACADEMICO a');
    }
}