<?php

/**
 * ACCIONXPERFIL
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ACCIONXPERFIL extends BaseACCIONXPERFIL
{
    
    public function getMODULO() {
        $query = Doctrine_Query::create()->from('MODULO mod')
                    ->where('mod.idModulo = ?', $this->idmodulo);
        return $query->fetchOne();
    }
    
    
//    public static function obtenerACCIONXPERFIL(PERFIL $perfil){
//        
//        $query = Doctrine_Query::create()->from('ACCIONXPERFIL pxa')
//                    ->where('pxa.idPerfil = ?', $perfil->idperfil)->distinct();
//        
//        return $query->fetchArray();
//        
//    }
    
}
