<?php

/**
 * ACCIONTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ACCIONTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ACCIONTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ACCION');
    }
}