<?php

/**
 * ACCIONXPERFILTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ACCIONXPERFILTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ACCIONXPERFILTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ACCIONXPERFIL');
    }
}