<?php

/**
 * ACTIVIDAD_UMATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ACTIVIDAD_UMATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ACTIVIDAD_UMATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ACTIVIDAD_UMA');
    }
}