<?php

/**
 * ACTIVIDADTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ACTIVIDADTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ACTIVIDADTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ACTIVIDAD');
    }
    
    public function ObtenerConsultaActividades(array $arrParamFiltro)
    {
        $query = Doctrine_Query::create()
                    ->select('a.idActividad, a.nombreActividad')
                    ->from('ACTIVIDAD a');
        return $query;
    }
}