<?php

/**
 * ACTXACT_UMATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ACTXACT_UMATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ACTXACT_UMATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ACTXACT_UMA');
    }
}