<?php

/**
 * AVANCE_ACTIVIDADTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AVANCE_ACTIVIDADTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AVANCE_ACTIVIDADTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AVANCE_ACTIVIDAD');
    }
}