<?php

/**
 * AVANCE_ACTIVIDADTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AVANCE_ACTIVIDADTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AVANCE_ACTIVIDADTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AVANCE_ACTIVIDAD');
    }
    
    public function ObtenerConsultaAvances(array $arrParamFiltro)
    {
        $query = Doctrine_Query::create()
                    ->select('avn.idAvanceActividad, avn.nombreAvance, avn.fechaInicioAv, avn.fechaFinAv, avn.fechaReporteAv, act.idActividad, act.nombreActividad')
                    ->from('AVANCE_ACTIVIDAD avn')
                    ->innerJoin('avn.ACTIVIDAD act');
        return $query;
    }
    
    public function ObtenerConsultaAvancePorActividad(ACTIVIDAD $actActividad)
    {
        $query = Doctrine_Query::create()
                    ->select('avn.idAvanceActividad, avn.nombreAvance, avn.fechaInicioAv, avn.fechaFinAv, avn.fechaReporteAv')
                    ->from('AVANCE_ACTIVIDAD avn')
                    ->where('avn.idActividad = ?', $actActividad->getIdactividad());
        return $query;
    }
}