<?php

/**
 * CARGOXUNIDAD_ORGTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CARGOXUNIDAD_ORGTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CARGOXUNIDAD_ORGTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CARGOXUNIDAD_ORG');
    }
}