<?php

/**
 * CARGOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CARGOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CARGOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CARGO');
    }
}