<?php

/**
 * CATEGORIA_UMATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CATEGORIA_UMATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CATEGORIA_UMATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CATEGORIA_UMA');
    }
}