<?php

/**
 * CIUDADTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CIUDADTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CIUDADTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CIUDAD');
    }
}