<?php

/**
 * DATO_ACTIVIDADTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DATO_ACTIVIDADTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DATO_ACTIVIDADTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DATO_ACTIVIDAD');
    }
}