<?php

/**
 * DIRECCIONTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DIRECCIONTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DIRECCIONTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DIRECCION');
    }
}