<?php

/**
 * DOC_IDENTIFICACIONTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DOC_IDENTIFICACIONTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DOC_IDENTIFICACIONTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DOC_IDENTIFICACION');
    }
}