<?php

/**
 * ESTADO_CIVILTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ESTADO_CIVILTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ESTADO_CIVILTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ESTADO_CIVIL');
    }
}