<?php

/**
 * ESTADO_ACTIVIDADTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ESTADO_ACTIVIDADTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ESTADO_ACTIVIDADTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ESTADO_ACTIVIDAD');
    }
}