<?php

/**
 * HISTORIAL_CARGOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HISTORIAL_CARGOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HISTORIAL_CARGOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HISTORIAL_CARGO');
    }
}