<?php

/**
 * HISTORIAL_GRADO_ACADTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HISTORIAL_GRADO_ACADTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HISTORIAL_GRADO_ACADTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HISTORIAL_GRADO_ACAD');
    }
}