<?php

/**
 * IDIOMATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IDIOMATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IDIOMATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IDIOMA');
    }
}