<?php

/**
 * MATERIATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MATERIATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MATERIATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MATERIA');
    }
}