<?php

/**
 * MUNICIPIOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MUNICIPIOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MUNICIPIOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MUNICIPIO');
    }
}