<?php

/**
 * NIVEL_ESTUDIOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NIVEL_ESTUDIOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NIVEL_ESTUDIOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NIVEL_ESTUDIO');
    }
}