<?php

/**
 * PAISTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PAISTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PAISTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PAIS');
    }
}