<?php

/**
 * PERFILTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PERFILTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PERFILTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PERFIL');
    }
}