<?php

/**
 * TEL_ACADEMICOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TEL_ACADEMICOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TEL_ACADEMICOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TEL_ACADEMICO');
    }
}