<?php

/**
 * TIEMPO_CONTRATACIONTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TIEMPO_CONTRATACIONTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TIEMPO_CONTRATACIONTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TIEMPO_CONTRATACION');
    }
}