<?php

/**
 * TIPO_SANGRETable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TIPO_SANGRETable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TIPO_SANGRETable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TIPO_SANGRE');
    }
}