<?php

/**
 * TIPO_ACTIVIDADTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TIPO_ACTIVIDADTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TIPO_ACTIVIDADTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TIPO_ACTIVIDAD');
    }
}