<?php

/**
 * TIPO_CONTRATACION_EXTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TIPO_CONTRATACION_EXTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TIPO_CONTRATACION_EXTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TIPO_CONTRATACION_EX');
    }
}