<?php

/**
 * TIPO_DOC_IDENTTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TIPO_DOC_IDENTTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TIPO_DOC_IDENTTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TIPO_DOC_IDENT');
    }
}