<?php

/**
 * TIPO_CONTRATACIONTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TIPO_CONTRATACIONTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TIPO_CONTRATACIONTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TIPO_CONTRATACION');
    }
}