<?php

/**
 * TIPO_CARGOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TIPO_CARGOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TIPO_CARGOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TIPO_CARGO');
    }
}