<?php

/**
 * TIPOXDATO_ACTTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TIPOXDATO_ACTTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TIPOXDATO_ACTTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TIPOXDATO_ACT');
    }
}