<?php

/**
 * TITULO_ACADEMICOTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TITULO_ACADEMICOTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TITULO_ACADEMICOTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TITULO_ACADEMICO');
    }
}