<?php

/**
 * UNIDAD_ORGANIZATIVATable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UNIDAD_ORGANIZATIVATable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UNIDAD_ORGANIZATIVATable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UNIDAD_ORGANIZATIVA');
    }
}