<?php

/**
 * UNIDAD_ORGANIZATIVA
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SEA-UCA_v1.0
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UNIDAD_ORGANIZATIVA extends BaseUNIDAD_ORGANIZATIVA
{
}
