<?php

/**
 * VALOR_DATO_ACTTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VALOR_DATO_ACTTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VALOR_DATO_ACTTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VALOR_DATO_ACT');
    }
}