<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/01 20:30:05
sfConfig::add(array(
  'app_url_base' => 'http://sea.uca.edu.sv',
  'app_url_imagenes' => 'http://sea.uca.edu.sv/images',
));
