<?php
// auto-generated by sfSecurityConfigHandler
// date: 2011/07/17 07:40:02
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'indexerror404' => 
  array (
    'is_secure' => false,
  ),
  'indexlogin' => 
  array (
    'is_secure' => false,
  ),
);
