<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/10 21:23:17
sfConfig::add(array(
  'app_url_base' => 'http://sea.uca.edu.sv',
  'app_url_imagenes' => 'http://sea.uca.edu.sv/images',
  'app_max_items_lista' => 20,
));
